---
- name: Pull latest image
  become: true
  community.docker.docker_image:
    name: ghcr.io/taubel/cloud-app:latest
    source: pull
  register: pulled_image

- name: Deploy app
  become: true
  community.docker.docker_container:
    name: cloud_app
    image: ghcr.io/taubel/cloud-app:{{ app_image }}
    state: started
    recreate: "{{ pulled_image.changed }}"
    restart: "{{ pulled_image.changed }}"
    ports:
      - 80:8000
