name: "Terraform Plan"

on:
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "Taubel"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "learn-terraform-github-actions"
  TF_VAR_ssh_public_key: "${{ secrets.SSH_PUBLIC_KEY }}"
  CONFIG_DIRECTORY: "./"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

jobs:
  terraform:
    if: github.repository != 'hashicorp-education/learn-terraform-github-actions'
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init & Plan
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform show -json tfplan > plan.json

      - name: Extract Plan Output
        id: plan-output
        run: |
          add=$(jq '.resource_changes | map(select(.change.actions | index("create"))) | length' plan.json)
          change=$(jq '.resource_changes | map(select(.change.actions | index("update"))) | length' plan.json)
          destroy=$(jq '.resource_changes | map(select(.change.actions | index("delete"))) | length' plan.json)
          echo "add=$add" >> $GITHUB_OUTPUT
          echo "change=$change" >> $GITHUB_OUTPUT
          echo "destroy=$destroy" >> $GITHUB_OUTPUT
